# Generated by Django 4.1.3 on 2022-11-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=1000)),
                ('domain', models.CharField(max_length=100)),
                ('hardness', models.CharField(choices=[('e', 'Easy'), ('m', 'Medium'), ('h', 'Hard')], max_length=1)),
            ],
        ),
    ]
