# Generated by Django 4.1.3 on 2022-11-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='domain',
            field=models.CharField(choices=[('1', 'Energy'), ('2', 'Electronics'), ('3', 'Electrical'), ('4', 'AI/ML'), ('5', 'Vehicle Development'), ('6', 'Robotics')], max_length=100),
        ),
    ]
