# Generated by Django 4.1.3 on 2022-11-10 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_ques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ques',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='ques',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ques',
            name='name',
        ),
        migrations.CreateModel(
            name='Stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='state.ques')),
            ],
        ),
    ]
